### ISSUE TITLE
Regarding Installation

### ISSUE THREAD

**Issue by vamsi8106** [zerosansan/td3_ddpg_sac_dqn_qlearning_sarsa_mobile_robot_navigation#2]
Hello sir
I have a bit of confusion regarding the first two installation steps you mentioned ,sir. Could you please provide a more detailed explanation of the entire process? I attempted to follow the steps you provided, but I seem to be encountering several errors. I believe I may be missing something crucial in the process. Can you please clarify the steps for me so that I can better understand and resolve the issues I'm experiencing?

**Comment by zerosansan** [comment]
Hi! Can you paste your error logs here?

For the first step, you should git clone these two repositories (https://wiki.ros.org/turtlebot3, https://wiki.ros.org/turtlebot3_gazebo) into your catkin workspace's `catkin_ws/src` folder and then run `catkin_make` to compile the workspace. Once you've confirmed that the workspace has successfully compiled, you can go ahead and clone my repository to get the following folders (`turtlebot3_simulation`, `turtlebot3_description`).

1. The `turtlebot3_description` directory should be placed in the `turtlebot3` directory (cloned from https://wiki.ros.org/turtlebot3). The directory hierarchy should look like this.
> `catkin_ws/src/turtlebot3/turtlebot3/turtlebot3_description`

2. Similarly, the `turtlebot3_simulation` directory should be placed in the turtlebot3 directory too (cloned from https://wiki.ros.org/turtlebot3). The directory hierarchy should look like this.
>  `catkin_ws/src/turtlebot3/turtlebot3_simulations`

Let me know if you still have problems with the setup. Thanks

**Comment by vamsi8106** [comment]
Thank you, sir this issue is resolved.
