### ISSUE TITLE
Error after launching "roslaunch turtlebot3_rl_sim start_td3_training.launch"

### ISSUE THREAD

**Issue by vamsi8106** [zerosansan/td3_ddpg_sac_dqn_qlearning_sarsa_mobile_robot_navigation#3]
Hello sir, I am getting the below after launching "roslaunch turtlebot3_rl_sim start_td3_training.launch". I tried to solve it many times. please help me to resolve this issue, sir.

**error:**
user@user:~/turtlebot3_ws$ roslaunch turtlebot3_rl_sim start_td3_training.launch
... logging to /home/user/.ros/log/7bde750c-7fe1-11ee-b68b-6185d6c00012/roslaunch-user-8755.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://user:40827/

SUMMARY
========

PARAMETERS
 * /rosdistro: noetic
 * /rosversion: 1.16.0
 * /stage_number: 1
 * /turtlebot3/actor_alpha: 0.0003
 * /turtlebot3/angular_speed: 0.3
 * /turtlebot3/critic_alpha: 0.0003
 * /turtlebot3/desired_pose/x: -1.0
 * /turtlebot3/desired_pose/y: 1.0
 * /turtlebot3/desired_pose/z: 0.0
 * /turtlebot3/gamma: 0.99
 * /turtlebot3/linear_forward_speed: 0.5
 * /turtlebot3/linear_turn_speed: 0.05
 * /turtlebot3/max_scan_range: 0.6
 * /turtlebot3/min_scan_range: 0.12
 * /turtlebot3/nepisodes: 1510
 * /turtlebot3/nsteps: 1000
 * /turtlebot3/scan_ranges: 360
 * /turtlebot3/stage_name: trajectory_test
 * /turtlebot3/starting_pose/x: 0.75
 * /turtlebot3/starting_pose/y: -0.75
 * /turtlebot3/starting_pose/z: 0.0
 * /turtlebot3/tau: 0.005

NODES
  /
    turtlebot3_td3 (turtlebot3_rl_sim/turtlebot3_rl_sim/src/start_td3_training.py)

ROS_MASTER_URI=http://localhost:11311/

ERROR: cannot launch node of type [turtlebot3_rl_sim/turtlebot3_rl_sim/src/start_td3_training.py]: Cannot locate node of type [turtlebot3_rl_sim/src/start_td3_training.py] in package [turtlebot3_rl_sim]. Make sure file exists in package path and permission is set to executable (chmod +x)
No processes to monitor
shutting down processing monitor...
... shutting down processing monitor complete

**Comment by zerosansan** [comment]
Hi. It looks like you will need to set the .py files to be executable. Try running `chmod +x start_td3_training.py` in your command line interface in the turtlebot3_rl_sim/src directory.

Let me know if this solved it.

**Comment by vamsi8106** [comment]
I have done it, sir. The Error is not getting resolved.  Even I restarted my PC and tried to run the code.

**Comment by zerosansan** [comment]
Hi. Can you paste the contents of `/home/user/.ros/log/7bde750c-7fe1-11ee-b68b-6185d6c00012/roslaunch-user-8755.log`?

**Comment by vamsi8106** [comment]
Hello, sir. Here, I am attaching my log file . Please review and tell me the error I am making.
[log_file.txt](https://github.com/zerosansan/td3_ddpg_sac_dqn_qlearning_sarsa_mobile_robot_navigation/files/13402374/log_file.txt)

**Comment by zerosansan** [comment]
Hi. Apologies for the late reply. Did you manage to solve the issue?

Some things to try is to `chmod +x` these .py files: 

1. start_td3_training.py
2. utils.py
3. environment_stage_1_nobonus.py

Let me know if you still have issues
